//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loksim3D.WetterEdit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loksim3D.WetterEdit.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string AboutWndDateColon {
            get {
                return ResourceManager.GetString("AboutWndDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version:.
        /// </summary>
        public static string AboutWndProdVersColon {
            get {
                return ResourceManager.GetString("AboutWndProdVersColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WeatherEdit.
        /// </summary>
        public static string AboutWndTitle {
            get {
                return ResourceManager.GetString("AboutWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loksim3D is a freeware application and can be used at no charge. A commercial usage, leasing or sale of the product is prohibited. The copyright owners of this program are Ralf Gryga, Lukas Haselsteiner, Uwe Klein and Martin Mory.
        ///
        ///Für irgendwelche Schäden, die sich aus der Nutzung des Simulators ergeben sollten, wird keinerlei Haftung übernommen..
        /// </summary>
        public static string AboutWndTxt {
            get {
                return ResourceManager.GetString("AboutWndTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above.
        /// </summary>
        public static string Above {
            get {
                return ResourceManager.GetString("Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Weatherfile.
        /// </summary>
        public static string AddNewWeatherFile {
            get {
                return ResourceManager.GetString("AddNewWeatherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Variable.
        /// </summary>
        public static string AddVariable {
            get {
                return ResourceManager.GetString("AddVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes
        ///Would you like to save these changes?.
        /// </summary>
        public static string AppCloseUnsavedChanges {
            get {
                return ResourceManager.GetString("AppCloseUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loksim WeatherEdit.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorColon {
            get {
                return ResourceManager.GetString("AuthorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness:.
        /// </summary>
        public static string BrightnessColon {
            get {
                return ResourceManager.GetString("BrightnessColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Image.
        /// </summary>
        public static string ClearImage {
            get {
                return ResourceManager.GetString("ClearImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        public static string CopyGestureText {
            get {
                return ResourceManager.GetString("CopyGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+X.
        /// </summary>
        public static string CutGestureText {
            get {
                return ResourceManager.GetString("CutGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Variable.
        /// </summary>
        public static string DeleteVariable {
            get {
                return ResourceManager.GetString("DeleteVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation:.
        /// </summary>
        public static string DokuColon {
            get {
                return ResourceManager.GetString("DokuColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Cab File.
        /// </summary>
        public static string DrivingCabFile {
            get {
                return ResourceManager.GetString("DrivingCabFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the driving cab of an engine.
        /// </summary>
        public static string DrivingCabFileDescription {
            get {
                return ResourceManager.GetString("DrivingCabFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file {0}:
        ///{1}.
        /// </summary>
        public static string ErrorLoadingFile_0_Msg_1_ {
            get {
                return ResourceManager.GetString("ErrorLoadingFile_0_Msg_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        public static string File_0_NotFound {
            get {
                return ResourceManager.GetString("File_0_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Properties.
        /// </summary>
        public static string FileProperties {
            get {
                return ResourceManager.GetString("FileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving {0}:
        ///{1}.
        /// </summary>
        public static string FileSaveError {
            get {
                return ResourceManager.GetString("FileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Files.
        /// </summary>
        public static string FilesBmp {
            get {
                return ResourceManager.GetString("FilesBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string FilesDoku {
            get {
                return ResourceManager.GetString("FilesDoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string FilesImages {
            get {
                return ResourceManager.GetString("FilesImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loksim Files.
        /// </summary>
        public static string FilesLoksim {
            get {
                return ResourceManager.GetString("FilesLoksim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Files.
        /// </summary>
        public static string FilesSky {
            get {
                return ResourceManager.GetString("FilesSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Files.
        /// </summary>
        public static string FilesWeather {
            get {
                return ResourceManager.GetString("FilesWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image from Clipboard.
        /// </summary>
        public static string ImageFromClipboard {
            get {
                return ResourceManager.GetString("ImageFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info:.
        /// </summary>
        public static string InfoColon {
            get {
                return ResourceManager.GetString("InfoColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.loksim3d.de.
        /// </summary>
        public static string LoksimWebsite {
            get {
                return ResourceManager.GetString("LoksimWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainMenuEdit {
            get {
                return ResourceManager.GetString("MainMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainMenuEditSettings {
            get {
                return ResourceManager.GetString("MainMenuEditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainMenuFileClose {
            get {
                return ResourceManager.GetString("MainMenuFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MainMenuFileNew {
            get {
                return ResourceManager.GetString("MainMenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string MainMenuFileOpen {
            get {
                return ResourceManager.GetString("MainMenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string MainMenuFileProperties {
            get {
                return ResourceManager.GetString("MainMenuFileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MainMenuFileRecent {
            get {
                return ResourceManager.GetString("MainMenuFileRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MainMenuFileSave {
            get {
                return ResourceManager.GetString("MainMenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MainMenuFileSaveAs {
            get {
                return ResourceManager.GetString("MainMenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string MainMenuHelp {
            get {
                return ResourceManager.GetString("MainMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about Loksim WeatherEdit.
        /// </summary>
        public static string MainMenuHelpAbout {
            get {
                return ResourceManager.GetString("MainMenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Image.
        /// </summary>
        public static string OtherImage {
            get {
                return ResourceManager.GetString("OtherImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        public static string PasteGestureText {
            get {
                return ResourceManager.GetString("PasteGestureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string PathColon {
            get {
                return ResourceManager.GetString("PathColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a positive number.
        /// </summary>
        public static string PositiveFloatValidation {
            get {
                return ResourceManager.GetString("PositiveFloatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a positive integer.
        /// </summary>
        public static string PositiveIntegerValidation {
            get {
                return ResourceManager.GetString("PositiveIntegerValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation (Alpha).
        /// </summary>
        public static string Precipitation {
            get {
                return ResourceManager.GetString("Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls Precipitation in this timespan.
        /// </summary>
        public static string PrecipitationDescription {
            get {
                return ResourceManager.GetString("PrecipitationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propability:.
        /// </summary>
        public static string PropabilityColon {
            get {
                return ResourceManager.GetString("PropabilityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Weatherfile.
        /// </summary>
        public static string RemoveWeatherFile {
            get {
                return ResourceManager.GetString("RemoveWeatherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default author:.
        /// </summary>
        public static string SettingsDefaultFileAuthorColon {
            get {
                return ResourceManager.GetString("SettingsDefaultFileAuthorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default fileinfo:.
        /// </summary>
        public static string SettingsDefaultFileInfoColon {
            get {
                return ResourceManager.GetString("SettingsDefaultFileInfoColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string SettingsLanguageColon {
            get {
                return ResourceManager.GetString("SettingsLanguageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change requires restart of application.
        /// </summary>
        public static string SettingsLanguageRestart {
            get {
                return ResourceManager.GetString("SettingsLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no write permissions....
        /// </summary>
        public static string SettingsUacStartMode {
            get {
                return ResourceManager.GetString("SettingsUacStartMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask what to do.
        /// </summary>
        public static string SettingsUacStartModeAsk {
            get {
                return ResourceManager.GetString("SettingsUacStartModeAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sightdistance:.
        /// </summary>
        public static string SightdistanceColon {
            get {
                return ResourceManager.GetString("SightdistanceColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyfile.
        /// </summary>
        public static string SkyFile {
            get {
                return ResourceManager.GetString("SkyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combines some Weatherfiles into one file that allows to select a sky.
        /// </summary>
        public static string SkyFileDescription {
            get {
                return ResourceManager.GetString("SkyFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowfall.
        /// </summary>
        public static string Snowfall {
            get {
                return ResourceManager.GetString("Snowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start as Admin.
        /// </summary>
        public static string UacDlgBtnAdmin {
            get {
                return ResourceManager.GetString("UacDlgBtnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not start as Admin.
        /// </summary>
        public static string UacDlgBtnNoAdmin {
            get {
                return ResourceManager.GetString("UacDlgBtnNoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No write permission.
        /// </summary>
        public static string UacDlgCaption {
            get {
                return ResourceManager.GetString("UacDlgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save choice and do not ask again.
        /// </summary>
        public static string UacDlgCheckBoxText {
            get {
                return ResourceManager.GetString("UacDlgCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeatherEdit does not have wright permissions in the current directory.
        /// </summary>
        public static string UacDlgInstructionText {
            get {
                return ResourceManager.GetString("UacDlgInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For saving files write permissions are needed.
        ///Do you want to restart WetherEdit with administrative privileges to gain write permissions?.
        /// </summary>
        public static string UacDlgText {
            get {
                return ResourceManager.GetString("UacDlgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be used in a variable name..
        /// </summary>
        public static string VarValidation_0_Illegal {
            get {
                return ResourceManager.GetString("VarValidation_0_Illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a variable name..
        /// </summary>
        public static string VarValidationEmpty {
            get {
                return ResourceManager.GetString("VarValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variablenames cannot start with numbers..
        /// </summary>
        public static string VarValidationNumber {
            get {
                return ResourceManager.GetString("VarValidationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weatherfile.
        /// </summary>
        public static string WeatherFile {
            get {
                return ResourceManager.GetString("WeatherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the weather for a whole day.
        /// </summary>
        public static string WeatherFileDescription {
            get {
                return ResourceManager.GetString("WeatherFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string WeatherFileDown {
            get {
                return ResourceManager.GetString("WeatherFileDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The higher this propability the more likely this weather will be choose when using random weahter selection.
        /// </summary>
        public static string WeatherFilePropabilityDescription {
            get {
                return ResourceManager.GetString("WeatherFilePropabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string WeatherFileUp {
            get {
                return ResourceManager.GetString("WeatherFileUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Timerange.
        /// </summary>
        public static string WthAddTimerange {
            get {
                return ResourceManager.GetString("WthAddTimerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Day.
        /// </summary>
        public static string WthBrightnessDay {
            get {
                return ResourceManager.GetString("WthBrightnessDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Brightness.
        /// </summary>
        public static string WthBrightnessFactor {
            get {
                return ResourceManager.GetString("WthBrightnessFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Night.
        /// </summary>
        public static string WthBrightnessNight {
            get {
                return ResourceManager.GetString("WthBrightnessNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption (Text for Weather Selection).
        /// </summary>
        public static string WthCaption {
            get {
                return ResourceManager.GetString("WthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Dawn.
        /// </summary>
        public static string WthDawnBegin {
            get {
                return ResourceManager.GetString("WthDawnBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Dawn.
        /// </summary>
        public static string WthDawnEnd {
            get {
                return ResourceManager.GetString("WthDawnEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Timerange.
        /// </summary>
        public static string WthDeleteTimerange {
            get {
                return ResourceManager.GetString("WthDeleteTimerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Dusk.
        /// </summary>
        public static string WthDuskBegin {
            get {
                return ResourceManager.GetString("WthDuskBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Dusk.
        /// </summary>
        public static string WthDuskEnd {
            get {
                return ResourceManager.GetString("WthDuskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illumination.
        /// </summary>
        public static string WthIllumination {
            get {
                return ResourceManager.GetString("WthIllumination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sightdirection:.
        /// </summary>
        public static string WthSightDirColon {
            get {
                return ResourceManager.GetString("WthSightDirColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sightdistance.
        /// </summary>
        public static string WthSightdistance {
            get {
                return ResourceManager.GetString("WthSightdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skybox.
        /// </summary>
        public static string WthSkybox {
            get {
                return ResourceManager.GetString("WthSkybox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texturefile.
        /// </summary>
        public static string WthSkyboxDescTexture {
            get {
                return ResourceManager.GetString("WthSkyboxDescTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h. tiles.
        /// </summary>
        public static string WthSkyboxDescTextureTileU {
            get {
                return ResourceManager.GetString("WthSkyboxDescTextureTileU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v. tiles.
        /// </summary>
        public static string WthSkyboxDescTextureTileV {
            get {
                return ResourceManager.GetString("WthSkyboxDescTextureTileV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of horizontal tiles.
        /// </summary>
        public static string WthSkyboxDescToolTipTextureTileU {
            get {
                return ResourceManager.GetString("WthSkyboxDescToolTipTextureTileU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of vertical tiles.
        /// </summary>
        public static string WthSkyboxDescToolTipTextureTileV {
            get {
                return ResourceManager.GetString("WthSkyboxDescToolTipTextureTileV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture above.
        /// </summary>
        public static string WthSkyboxTexAbove {
            get {
                return ResourceManager.GetString("WthSkyboxTexAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture on the right (East).
        /// </summary>
        public static string WthSkyboxTexEast {
            get {
                return ResourceManager.GetString("WthSkyboxTexEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture ahead (North).
        /// </summary>
        public static string WthSkyboxTexNorth {
            get {
                return ResourceManager.GetString("WthSkyboxTexNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture behind (South).
        /// </summary>
        public static string WthSkyboxTexSouth {
            get {
                return ResourceManager.GetString("WthSkyboxTexSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture on the left (West).
        /// </summary>
        public static string WthSkyboxTexWest {
            get {
                return ResourceManager.GetString("WthSkyboxTexWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string WthTest {
            get {
                return ResourceManager.GetString("WthTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeranges.
        /// </summary>
        public static string WthTimeRanges {
            get {
                return ResourceManager.GetString("WthTimeRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to test:.
        /// </summary>
        public static string WthTimeToTestColon {
            get {
                return ResourceManager.GetString("WthTimeToTestColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can define custom variables or use predefined ones.
        ///Variables can be used to control the visibility of objects or sounds..
        /// </summary>
        public static string WthVarsDescription {
            get {
                return ResourceManager.GetString("WthVarsDescription", resourceCulture);
            }
        }
    }
}
