#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_L3DPACKAGEINSTALLER                 107
#define IDC_L3DPACKAGEINSTALLER                 109
#define IDD_INSTALLPACKAGES                     111
#define IDD_INSTALLSELECTFILES                  113
#define IDI_GOUP                                120
#define IDI_GODOWN                              122
#define IDD_DEINSTALLPKGSEARCH                  124
#define IDD_DEINSTALLSELECTFILES                126
#define IDD_MAINPKGINSTALLER                    128
#define IDD_SETTINGS                            130
#define IDD_DBUPDATE                            131
#define IDI_LOKSIM3D                            132
#define IDD_ABOUTBOX                            133
#define IDD_UNDOOPERATION                       136
#define IDD_FILEDEPENDENCIES                    137
#define IDI_FILE_FONT                           139
#define IDI_FILE_FPL                            141
#define IDI_FILE_GRP                            143
#define IDI_FILE_KBS                            145
#define IDI_FILE_LOK                            148
#define IDI_FILE_OBJ                            149
#define IDI_FILE_PACK                           151
#define IDI_FILE_RAIL                           153
#define IDI_FILE_SKY                            155
#define IDI_FILE_STR                            157
#define IDI_FILE_WTH                            159
#define IDI_FILE_STAT                           161
#define IDC_ABOUT_KOMPEX                        1000
#define IDC_BUTTONCANCELUNDO                    1000
#define IDC_BUTTONREMOVEPACKAGE                 1000
#define IDC_STATICDEINSTALLFILESDLGTXT          1000
#define IDC_STATICL3DPATH                       1000
#define IDC_ABOUT_VERSION                       1001
#define IDC_LISTDEINSTALLSELECTEDPKGS           1001
#define IDC_PROGRESSINSTALL                     1001
#define IDC_SET_ALLOW_UNDO                      1001
#define IDC_TABCTRLMAIN                         1001
#define IDC_BUTTONUNDO                          1002
#define IDC_COMBOLANG                           1002
#define IDC_LISTPACKAGES                        1002
#define IDC_ABOUT_LOKSIM                        1003
#define IDC_EDITREADME                          1003
#define IDC_INSTSELECTFSMTIME                   1003
#define IDC_LISTUNDOPACKAGES                    1003
#define IDC_SET_UN_ASK                          1003
#define IDC_STATICPROGRESSINSTALL               1003
#define IDC_ABOUT_SHA                           1004
#define IDC_BUTTONSTARTINSTALLATION             1004
#define IDC_LISTALLPACKAGES                     1004
#define IDC_SET_IN_ONLYOLDER                    1004
#define IDC_BUTTONCANCELINSTALLATION            1005
#define IDC_DEINSTSTALLFSMTIME                  1005
#define IDC_EDITFILTER                          1005
#define IDC_INSTSELECTPKGMTIME                  1005
#define IDC_SET_IN_ASK                          1005
#define IDC_ABOUT_ZIP                           1006
#define IDC_STATICPKGINFO                       1006
#define IDC_STATIC_INST_L3D_PATH                1006
#define IDC_TREEFILESCHECKABLE                  1006
#define IDC_BUTTONSTARTDEINSTALL                1007
#define IDC_STATICDEINSTALLFSMT                 1007
#define IDC_BUTTONCANCELDEINSTALL               1008
#define IDC_TREEFILESNOTCHECKABLE               1008
#define IDC_STATICDEINSTALLLEFT                 1009
#define IDC_CHECKBOXASKBEFOREDEINSTALL          1010
#define IDC_STATICDEINSTALLRIGHTTOP             1011
#define IDC_STATICDEINSTALLRIGHTBOTTOM          1012
#define IDC_STATICFILTER                        1013
#define IDC_STATICREADME                        1014
#define IDC_LISTALLFILES                        1015
#define IDC_LISTDEPENDENCIES                    1016
#define IDC_EDITINSTALLAT                       1017
#define IDC_EDITFILEOVERWRITTEN                 1018
#define IDC_EDITFILEPATH                        1019
#define IDC_STATICINSTALLAT                     1020
#define IDC_STATICFILEOVERWRITTEN               1021
#define IDC_STATICFILEPATH                      1022
#define IDC_STATICFILEEXISTED                   1023
#define IDC_EDITFILEEXISTED                     1024
#define IDC_BACKUPDIRECTORY                     1025
#define IDC_EDITCHECKSUM                        1026
#define IDC_STATICCHECKSUM                      1027
#define IDC_PROGRESS                            1028
#define IDC_EXPORTFILELIST                      40000
#define IDM_SETTINGS                            40000
#define IDS_LOADING_README                      40000
#define IDS_APP_TITLE                           40001
#define IDS_INSTALLPKGFILEFILTERDESC            40002
#define IDS_INSTALLPKGFILEFILTEREXT             40003
#define IDC_CHECKBOXONLYOLDER                   40004
#define IDS_INSTALLPROGTXT                      40004
#define IDS_INSTALLSUCCESSFUL                   40005
#define IDC_CHECKBOXASKALWAYS                   40006
#define IDS_INSTALLSUCCESSFULTITLE              40006
#define IDS_INSTALLCANCELLED                    40007
#define IDC_BUTTONADDPACKAGES                   40008
#define IDS_INSTALLCANCELLEDTITLE               40008
#define IDS_INSTALLCANCELLEDTITLE1              40008
#define IDS_INSTALLROLLEDBACK                   40009
#define IDS_INSTALLPARTIAL                      40010
#define IDS_INSTALLERRORFS                      40011
#define IDS_INSTALLERRORTXFS                    40012
#define IDC_BUTTONUP                            40013
#define IDS_INSTALLERRORZIP                     40013
#define IDS_INSTALLERROR                        40014
#define IDC_BUTTONDOWN                          40015
#define IDS_INSTALLERRORHEADER                  40015
#define IDC_EDITPACKAGEINFO                     40016
#define IDC_STATICSELECTINSTALLFILES            40016
#define IDS_HEADERINSTALLSELECTFILES            40016
#define IDS_HEADERINSTALLSHOWFILES              40017
#define IDS_HEADERINSTALLSHOWFILESEXISTING      40017
#define IDC_STATICSHOWINSTALLFILES              40018
#define IDS_SELECTFILESTVINSTALLNEW             40018
#define IDS_SELECTFILESTVWRITEPROTINSTALL       40019
#define IDS_SELECTFILESTVDELETE                 40020
#define IDS_SELECTFILESTVWRITEPROTDELETE        40021
#define IDS_SHOWFILESTVINSTALLEDNEW             40022
#define IDS_SHOWFILESTVWRITEPROTINSTALLED       40023
#define IDS_SHOWFILESTVDELETED                  40024
#define IDS_SHOWFILESTVWRITEPROTDELETED         40025
#define IDS_WARNINGCANCELTITLE                  40026
#define IDS_WARNINGCANCEL                       40027
#define IDS_PACKAGENAME                         40028
#define IDS_INSTALLEDON                         40029
#define IDS_HEADERDEINSTALLSELECTFILES          40030
#define IDS_HEADERDEINSTALLSHOWFILES            40031
#define IDC_PROGRESSDEINSTALL                   40032
#define IDS_DEINSTALLSELECTFILESSHOW            40032
#define IDC_STATICPROGRESSDEINSTALL             40033
#define IDS_DEINSTALLSELECTFILES                40033
#define IDS_DEINSTALLERRORFILETXT               40034
#define IDS_DEINSTALLERRORTXT                   40035
#define IDS_DEINSTALLERRORHEADER                40036
#define IDS_DEINSTALLERRORUNKWOWN               40037
#define IDS_DEINSTALLSUCCESSHEADER              40038
#define IDS_DEINSTALLSUCCESSTXT                 40039
#define IDS_WARNINGDEINSTALLCANCEL              40040
#define IDS_WARNINGDEINSTALLCANCELTITLE         40041
#define IDS_DEINSTALLCANCELLDTITLE              40042
#define IDS_TAB_HEADER_INSTALL                  40043
#define IDS_TAB_HEADER_DEINSTALL                40044
#define IDS_TAB_HEADER_FILEDEPENDENCIES         40045
#define IDS_SETTINGS_SAVE_ERROR                 40046
#define IDS_ERRORACCESS                         40047
#define IDS_ERRORDB                             40048
#define IDS_ZIP_ERR_NOFILE                      40049
#define IDS_ZIP_ERR_CORRUPT                     40050
#define IDS_ZIP_ERR_READ                        40051
#define IDS_UNDOTYPE                            40052
#define IDS_UNDODEORINSTALLEDON                 40053
#define IDS_UNDOINSTALLATION                    40054
#define IDS_UNDODEINSTALL                       40055
#define IDS_TAB_HEADER_UNDO                     40056
#define IDS_SELECTFILESTVINSTALLEXISTING        40057
#define IDS_SHOWFILESTVINSTALLEDEXISTING        40058
#define IDS_LANG_DE                             40059
#define IDS_LANG_EN                             40060
#define IDS_PKGVERSIONNEWER                     40061
#define IDS_ALWAYSASKNOTPOSSIBLE                40062
#define IDS_ERR_CREATE_DIR                      40063
#define IDS_ERR_PATH_DOES_NOT_EXIST             40064
#define IDS_FENCY_APP_TITLE                     40065
#define IDS_DEINSTALLED_PKG_HEADER              40066
#define IDS_YES                                 40067
#define IDS_NO                                  40068
#define IDS_EXPORTLISTTIMEPKG                   40069
#define IDS_EXPORTLISTTIMEFS                    40070
